<a href="https://colab.research.google.com/github/0902338471/SCWR/blob/master/CinnamonAI_NeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Hu-moment**

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import copy

In [0]:
class NeuralNet:
  def __init__(self,layers_dims):
    self.params = {}
    self.init_params(layers_dims)
  def init_params(self,layer_dims):
    ###initializing weight and bias for each layer using given layer_dims
    self.num_hidden_layers = len(layer_dims)-1
    for i in range(1,len(layer_dims)):
      self.params["W"+str(i)] = np.random.randn(layer_dims[i],layer_dims[i-1])
      self.params["b"+str(i)] = np.random.randn(layer_dims[i],1)
  def unit_forward_propagating(self,previous_input,weight,bias):
    ###calculate matrix operation and adding bias to unit input
    return np.add(np.matmul(previous_input,weight),bias)
  def softmax_function(self,a):
    return a/(np.sum(a))
  def forward_activate_output(self,activation,linear_input):
    ###activating input by using activation function
    if(activation=='sigmoid'):
      return 1.0/(1+np.exp(-linear_input))
    if(activation=="softmax"):
      return np.apply_along_axis(self.softmax_function,1,linear_input)
  def whole_forward_propagating(self,X):
    ###whole forward propagating process
    previous_input = copy.copy(X)
    for layer in range(1,self.num_hidden_layers):
      self.variables["Z"+str(layer)] = unit_forward_propagating(previous_input,self.params["W"+str(layer)],self.params["b"+str(layer)])
      if(layer == self.num_hidden_layers - 1):
        ###softmax activation for last layer
        self.variables["A"+str(layer)] = forward_activate_output(activation="softmax",self.variables["Z"+str(layer)])
      else:
        self.variables["A"+str(layer)] = forward_activate_output(activation="sigmoid",self.variables["Z"+str(layer)])
      previous_input = copy.copy(self.variables["A"+str(layer)])
  def categorical_to_one_hot(self,Y):
    num_class = np.max(Y)+1
    return np.eye(num_class)[Y]
  def compute_each_instances(self,unit_Y,unit_last_layer):
    ### unit_Y and unit_last_layer both have same shape of (n_class,1) (Y must be converted to one hot vector)
    return np.dot(unit_Y,unit_last_layer)
  def calculate_error_last_layer(self,)
  def cost_function(self,Y,last_layer):
    ###total cost over all examples
    Y_one_hot = self.categorical_to_one_hot(Y)
    cost = 0.0
    for index_example,example in enumerate(last_layer):
      cost += compute_each_instance(Y_one_hot[index_example],example)
    cost = -cost/m
    return cost
  def unit_backward_propagating(self,next_input):
  def backward_activate_output(self,weight,derive_linear_input):
    ###calculating derivative of J with respect to activation unit 
      return np.matmul(np.transpose(weight),derive_linear_input)
  def 
  def whole_backward_propagating(self,X):
    ###whole backward propagating process
  def fit_model(X):
    

The three outputs $(dW^{[l]}, db^{[l]}, dA^{[l-1]})$ are computed using the input $dZ^{[l]}$.Here are the formulas you need:
$$ dW^{[l]} = \frac{\partial \mathcal{J} }{\partial W^{[l]}} = \frac{1}{m} dZ^{[l]} A^{[l-1] T} \tag{8}$$
$$ db^{[l]} = \frac{\partial \mathcal{J} }{\partial b^{[l]}} = \frac{1}{m} \sum_{i = 1}^{m} dZ^{[l](i)}\tag{9}$$
$$ dA^{[l-1]} = \frac{\partial \mathcal{L} }{\partial A^{[l-1]}} = W^{[l] T} dZ^{[l]} \tag{10}$$

In [0]:
np.dot([1,2,3],[1,2,3])

14

In [0]:
def categorical_to_one_hot(Y):
  num_class = np.max(Y)+1
  return np.eye(num_class)[Y]

In [0]:
categorical_to_one_hot([1,2,3,0])

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])

In [0]:
-c

array([[-24, -15],
       [-54, -36]])

In [0]:
a=[[1,2,3],[4,5,6]]

array([[25, 16],
       [56, 38]])

In [0]:
def my_function(a):
  return a/(np.sum(a))

In [0]:
np.apply_along_axis(my_function,1,a)

array([[0.16666667, 0.33333333, 0.5       ],
       [0.26666667, 0.33333333, 0.4       ]])